{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $serviceName }}
    {{- include "doa-market.labels" $ | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: {{ $service.service.type | default $.Values.defaults.service.type }}
  ports:
    - port: {{ $service.service.port | default $.Values.defaults.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $serviceName }}
    {{- include "doa-market.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
