apiVersion: v2
name: doa-market
description: DOA Market Microservices Helm Chart
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - microservices
  - e-commerce
  - kubernetes

maintainers:
  - name: DOA Openmarket Team
    email: team@doa-market.com

dependencies: []
